package com.xj.project.transform.model;

import java.util.Date;

public class Journal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.student_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.student_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.title
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.content
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.pics
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String pics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.excellent
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Byte excellent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.read_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String readId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.read_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String readName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.read_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date readTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.view_count
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.comment_count
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.commit_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date commitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.score
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Float score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.comment
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.pic_urls
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String picUrls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.is_score
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Byte isScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_journal.is_excellent
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Byte isExcellent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.id
     *
     * @return the value of t_internship_journal.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.id
     *
     * @param id the value for t_internship_journal.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.task_id
     *
     * @return the value of t_internship_journal.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.task_id
     *
     * @param taskId the value for t_internship_journal.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.student_name
     *
     * @return the value of t_internship_journal.student_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.student_name
     *
     * @param studentName the value for t_internship_journal.student_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.student_id
     *
     * @return the value of t_internship_journal.student_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.student_id
     *
     * @param studentId the value for t_internship_journal.student_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.title
     *
     * @return the value of t_internship_journal.title
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.title
     *
     * @param title the value for t_internship_journal.title
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.content
     *
     * @return the value of t_internship_journal.content
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.content
     *
     * @param content the value for t_internship_journal.content
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.pics
     *
     * @return the value of t_internship_journal.pics
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.pics
     *
     * @param pics the value for t_internship_journal.pics
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPics(String pics) {
        this.pics = pics == null ? null : pics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.status
     *
     * @return the value of t_internship_journal.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.status
     *
     * @param status the value for t_internship_journal.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.excellent
     *
     * @return the value of t_internship_journal.excellent
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Byte getExcellent() {
        return excellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.excellent
     *
     * @param excellent the value for t_internship_journal.excellent
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setExcellent(Byte excellent) {
        this.excellent = excellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.read_id
     *
     * @return the value of t_internship_journal.read_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getReadId() {
        return readId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.read_id
     *
     * @param readId the value for t_internship_journal.read_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setReadId(String readId) {
        this.readId = readId == null ? null : readId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.read_name
     *
     * @return the value of t_internship_journal.read_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getReadName() {
        return readName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.read_name
     *
     * @param readName the value for t_internship_journal.read_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setReadName(String readName) {
        this.readName = readName == null ? null : readName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.read_time
     *
     * @return the value of t_internship_journal.read_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.read_time
     *
     * @param readTime the value for t_internship_journal.read_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.view_count
     *
     * @return the value of t_internship_journal.view_count
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.view_count
     *
     * @param viewCount the value for t_internship_journal.view_count
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.comment_count
     *
     * @return the value of t_internship_journal.comment_count
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.comment_count
     *
     * @param commentCount the value for t_internship_journal.comment_count
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.commit_time
     *
     * @return the value of t_internship_journal.commit_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getCommitTime() {
        return commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.commit_time
     *
     * @param commitTime the value for t_internship_journal.commit_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.score
     *
     * @return the value of t_internship_journal.score
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.score
     *
     * @param score the value for t_internship_journal.score
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setScore(Float score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.comment
     *
     * @return the value of t_internship_journal.comment
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.comment
     *
     * @param comment the value for t_internship_journal.comment
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.school_id
     *
     * @return the value of t_internship_journal.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.school_id
     *
     * @param schoolId the value for t_internship_journal.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.pic_urls
     *
     * @return the value of t_internship_journal.pic_urls
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPicUrls() {
        return picUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.pic_urls
     *
     * @param picUrls the value for t_internship_journal.pic_urls
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPicUrls(String picUrls) {
        this.picUrls = picUrls == null ? null : picUrls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.is_score
     *
     * @return the value of t_internship_journal.is_score
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Byte getIsScore() {
        return isScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.is_score
     *
     * @param isScore the value for t_internship_journal.is_score
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setIsScore(Byte isScore) {
        this.isScore = isScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_journal.is_excellent
     *
     * @return the value of t_internship_journal.is_excellent
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Byte getIsExcellent() {
        return isExcellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_journal.is_excellent
     *
     * @param isExcellent the value for t_internship_journal.is_excellent
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setIsExcellent(Byte isExcellent) {
        this.isExcellent = isExcellent;
    }
}