package com.xj.project.transform.model;

import java.util.Date;

public class Node {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.fid
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.node_type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer nodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.node_title
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String nodeTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.description
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.node_code
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String nodeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.node_path
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String nodePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.sort
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.creator_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.creator_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String creatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.create_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.updator_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String updatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.updator_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String updatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.update_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.principal_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String principalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.manager_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.city_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer cityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.id
     *
     * @return the value of t_node.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.id
     *
     * @param id the value for t_node.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.fid
     *
     * @return the value of t_node.fid
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.fid
     *
     * @param fid the value for t_node.fid
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.node_type
     *
     * @return the value of t_node.node_type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.node_type
     *
     * @param nodeType the value for t_node.node_type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setNodeType(Integer nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.node_title
     *
     * @return the value of t_node.node_title
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getNodeTitle() {
        return nodeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.node_title
     *
     * @param nodeTitle the value for t_node.node_title
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setNodeTitle(String nodeTitle) {
        this.nodeTitle = nodeTitle == null ? null : nodeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.description
     *
     * @return the value of t_node.description
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.description
     *
     * @param description the value for t_node.description
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.node_code
     *
     * @return the value of t_node.node_code
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getNodeCode() {
        return nodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.node_code
     *
     * @param nodeCode the value for t_node.node_code
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setNodeCode(String nodeCode) {
        this.nodeCode = nodeCode == null ? null : nodeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.node_path
     *
     * @return the value of t_node.node_path
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getNodePath() {
        return nodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.node_path
     *
     * @param nodePath the value for t_node.node_path
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setNodePath(String nodePath) {
        this.nodePath = nodePath == null ? null : nodePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.status
     *
     * @return the value of t_node.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.status
     *
     * @param status the value for t_node.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.sort
     *
     * @return the value of t_node.sort
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.sort
     *
     * @param sort the value for t_node.sort
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.creator_id
     *
     * @return the value of t_node.creator_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.creator_id
     *
     * @param creatorId the value for t_node.creator_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.creator_name
     *
     * @return the value of t_node.creator_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.creator_name
     *
     * @param creatorName the value for t_node.creator_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.create_time
     *
     * @return the value of t_node.create_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.create_time
     *
     * @param createTime the value for t_node.create_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.updator_id
     *
     * @return the value of t_node.updator_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getUpdatorId() {
        return updatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.updator_id
     *
     * @param updatorId the value for t_node.updator_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setUpdatorId(String updatorId) {
        this.updatorId = updatorId == null ? null : updatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.updator_name
     *
     * @return the value of t_node.updator_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getUpdatorName() {
        return updatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.updator_name
     *
     * @param updatorName the value for t_node.updator_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setUpdatorName(String updatorName) {
        this.updatorName = updatorName == null ? null : updatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.update_time
     *
     * @return the value of t_node.update_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.update_time
     *
     * @param updateTime the value for t_node.update_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.principal_id
     *
     * @return the value of t_node.principal_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPrincipalId() {
        return principalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.principal_id
     *
     * @param principalId the value for t_node.principal_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPrincipalId(String principalId) {
        this.principalId = principalId == null ? null : principalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.manager_id
     *
     * @return the value of t_node.manager_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.manager_id
     *
     * @param managerId the value for t_node.manager_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId == null ? null : managerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.city_id
     *
     * @return the value of t_node.city_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.city_id
     *
     * @param cityId the value for t_node.city_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
}