package com.xj.project.transform.model;

import java.util.Date;

public class Sign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.student_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.phone_uuid
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String phoneUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.lng
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Float lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.lat
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Float lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.sign_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date signTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.photo
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.province
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.city
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.district
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.street
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.audit_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.audit_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String auditName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.audit_user
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String auditUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.description
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.audit_status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Byte auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sign.pic_urls
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String picUrls;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.id
     *
     * @return the value of t_sign.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.id
     *
     * @param id the value for t_sign.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.student_id
     *
     * @return the value of t_sign.student_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.student_id
     *
     * @param studentId the value for t_sign.student_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.phone_uuid
     *
     * @return the value of t_sign.phone_uuid
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPhoneUuid() {
        return phoneUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.phone_uuid
     *
     * @param phoneUuid the value for t_sign.phone_uuid
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPhoneUuid(String phoneUuid) {
        this.phoneUuid = phoneUuid == null ? null : phoneUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.type
     *
     * @return the value of t_sign.type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.type
     *
     * @param type the value for t_sign.type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.lng
     *
     * @return the value of t_sign.lng
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Float getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.lng
     *
     * @param lng the value for t_sign.lng
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setLng(Float lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.lat
     *
     * @return the value of t_sign.lat
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Float getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.lat
     *
     * @param lat the value for t_sign.lat
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setLat(Float lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.sign_time
     *
     * @return the value of t_sign.sign_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getSignTime() {
        return signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.sign_time
     *
     * @param signTime the value for t_sign.sign_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setSignTime(Date signTime) {
        this.signTime = signTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.photo
     *
     * @return the value of t_sign.photo
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.photo
     *
     * @param photo the value for t_sign.photo
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.province
     *
     * @return the value of t_sign.province
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.province
     *
     * @param province the value for t_sign.province
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.city
     *
     * @return the value of t_sign.city
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.city
     *
     * @param city the value for t_sign.city
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.district
     *
     * @return the value of t_sign.district
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.district
     *
     * @param district the value for t_sign.district
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.street
     *
     * @return the value of t_sign.street
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.street
     *
     * @param street the value for t_sign.street
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.status
     *
     * @return the value of t_sign.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.status
     *
     * @param status the value for t_sign.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.audit_time
     *
     * @return the value of t_sign.audit_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.audit_time
     *
     * @param auditTime the value for t_sign.audit_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.audit_name
     *
     * @return the value of t_sign.audit_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.audit_name
     *
     * @param auditName the value for t_sign.audit_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName == null ? null : auditName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.audit_user
     *
     * @return the value of t_sign.audit_user
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.audit_user
     *
     * @param auditUser the value for t_sign.audit_user
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setAuditUser(String auditUser) {
        this.auditUser = auditUser == null ? null : auditUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.description
     *
     * @return the value of t_sign.description
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.description
     *
     * @param description the value for t_sign.description
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.school_id
     *
     * @return the value of t_sign.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.school_id
     *
     * @param schoolId the value for t_sign.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.audit_status
     *
     * @return the value of t_sign.audit_status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Byte getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.audit_status
     *
     * @param auditStatus the value for t_sign.audit_status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setAuditStatus(Byte auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.task_id
     *
     * @return the value of t_sign.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.task_id
     *
     * @param taskId the value for t_sign.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sign.pic_urls
     *
     * @return the value of t_sign.pic_urls
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPicUrls() {
        return picUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sign.pic_urls
     *
     * @param picUrls the value for t_sign.pic_urls
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPicUrls(String picUrls) {
        this.picUrls = picUrls == null ? null : picUrls.trim();
    }
}