package com.xj.project.transform.model;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.user_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.sid
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.grade
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.user_id
     *
     * @return the value of t_student.user_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.user_id
     *
     * @param userId the value for t_student.user_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.sid
     *
     * @return the value of t_student.sid
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.sid
     *
     * @param sid the value for t_student.sid
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.school_id
     *
     * @return the value of t_student.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.school_id
     *
     * @param schoolId the value for t_student.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.grade
     *
     * @return the value of t_student.grade
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.grade
     *
     * @param grade the value for t_student.grade
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }
}