package com.xj.project.transform.model;

public class SummaryWithBLOBs extends Summary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_summary.pics
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String pics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_internship_summary.pic_urls
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String picUrls;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_summary.pics
     *
     * @return the value of t_internship_summary.pics
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_summary.pics
     *
     * @param pics the value for t_internship_summary.pics
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPics(String pics) {
        this.pics = pics == null ? null : pics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_internship_summary.pic_urls
     *
     * @return the value of t_internship_summary.pic_urls
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPicUrls() {
        return picUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_internship_summary.pic_urls
     *
     * @param picUrls the value for t_internship_summary.pic_urls
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPicUrls(String picUrls) {
        this.picUrls = picUrls == null ? null : picUrls.trim();
    }
}