package com.xj.project.transform.model;

import java.util.Date;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.node_ids
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String nodeIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.username
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.nickname
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.real_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.password
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.create_user_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.create_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.email
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.email_validate
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer emailValidate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.mobile
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.mobile_validate
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer mobileValidate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.salt
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.last_login_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.wx_open_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String wxOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.qq_open_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String qqOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.user_type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.gender
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.id_card
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user.icon
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_id
     *
     * @return the value of t_sys_user.user_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_id
     *
     * @param userId the value for t_sys_user.user_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.school_id
     *
     * @return the value of t_sys_user.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.school_id
     *
     * @param schoolId the value for t_sys_user.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.node_ids
     *
     * @return the value of t_sys_user.node_ids
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getNodeIds() {
        return nodeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.node_ids
     *
     * @param nodeIds the value for t_sys_user.node_ids
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setNodeIds(String nodeIds) {
        this.nodeIds = nodeIds == null ? null : nodeIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.username
     *
     * @return the value of t_sys_user.username
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.username
     *
     * @param username the value for t_sys_user.username
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.nickname
     *
     * @return the value of t_sys_user.nickname
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.nickname
     *
     * @param nickname the value for t_sys_user.nickname
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.real_name
     *
     * @return the value of t_sys_user.real_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.real_name
     *
     * @param realName the value for t_sys_user.real_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.password
     *
     * @return the value of t_sys_user.password
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.password
     *
     * @param password the value for t_sys_user.password
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.create_user_id
     *
     * @return the value of t_sys_user.create_user_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.create_user_id
     *
     * @param createUserId the value for t_sys_user.create_user_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.create_time
     *
     * @return the value of t_sys_user.create_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.create_time
     *
     * @param createTime the value for t_sys_user.create_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.email
     *
     * @return the value of t_sys_user.email
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.email
     *
     * @param email the value for t_sys_user.email
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.email_validate
     *
     * @return the value of t_sys_user.email_validate
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getEmailValidate() {
        return emailValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.email_validate
     *
     * @param emailValidate the value for t_sys_user.email_validate
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setEmailValidate(Integer emailValidate) {
        this.emailValidate = emailValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.mobile
     *
     * @return the value of t_sys_user.mobile
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.mobile
     *
     * @param mobile the value for t_sys_user.mobile
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.mobile_validate
     *
     * @return the value of t_sys_user.mobile_validate
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getMobileValidate() {
        return mobileValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.mobile_validate
     *
     * @param mobileValidate the value for t_sys_user.mobile_validate
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setMobileValidate(Integer mobileValidate) {
        this.mobileValidate = mobileValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.salt
     *
     * @return the value of t_sys_user.salt
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.salt
     *
     * @param salt the value for t_sys_user.salt
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.last_login_time
     *
     * @return the value of t_sys_user.last_login_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.last_login_time
     *
     * @param lastLoginTime the value for t_sys_user.last_login_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.wx_open_id
     *
     * @return the value of t_sys_user.wx_open_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.wx_open_id
     *
     * @param wxOpenId the value for t_sys_user.wx_open_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.qq_open_id
     *
     * @return the value of t_sys_user.qq_open_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getQqOpenId() {
        return qqOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.qq_open_id
     *
     * @param qqOpenId the value for t_sys_user.qq_open_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setQqOpenId(String qqOpenId) {
        this.qqOpenId = qqOpenId == null ? null : qqOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.status
     *
     * @return the value of t_sys_user.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.status
     *
     * @param status the value for t_sys_user.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.user_type
     *
     * @return the value of t_sys_user.user_type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.user_type
     *
     * @param userType the value for t_sys_user.user_type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.gender
     *
     * @return the value of t_sys_user.gender
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.gender
     *
     * @param gender the value for t_sys_user.gender
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.id_card
     *
     * @return the value of t_sys_user.id_card
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.id_card
     *
     * @param idCard the value for t_sys_user.id_card
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user.icon
     *
     * @return the value of t_sys_user.icon
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user.icon
     *
     * @param icon the value for t_sys_user.icon
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}