package com.xj.project.transform.model;

import java.util.Date;

public class TaskConfigDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config_detail.plugin_key
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String pluginKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config_detail.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config_detail.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config_detail.plugin_key
     *
     * @return the value of t_task_config_detail.plugin_key
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getPluginKey() {
        return pluginKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config_detail.plugin_key
     *
     * @param pluginKey the value for t_task_config_detail.plugin_key
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setPluginKey(String pluginKey) {
        this.pluginKey = pluginKey == null ? null : pluginKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config_detail.task_id
     *
     * @return the value of t_task_config_detail.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config_detail.task_id
     *
     * @param taskId the value for t_task_config_detail.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config_detail.version
     *
     * @return the value of t_task_config_detail.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config_detail.version
     *
     * @param version the value for t_task_config_detail.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setVersion(Date version) {
        this.version = version;
    }
}