package com.xj.project.transform.model;

import java.util.Date;

public class TaskStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_student.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_student.task_group_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long taskGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_student.student_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_student.student_num
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String studentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_student.student_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_student.chanaged
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer chanaged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_student.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_student.attaches
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String attaches;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_student.task_id
     *
     * @return the value of t_task_student.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_student.task_id
     *
     * @param taskId the value for t_task_student.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_student.task_group_id
     *
     * @return the value of t_task_student.task_group_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getTaskGroupId() {
        return taskGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_student.task_group_id
     *
     * @param taskGroupId the value for t_task_student.task_group_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskGroupId(Long taskGroupId) {
        this.taskGroupId = taskGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_student.student_id
     *
     * @return the value of t_task_student.student_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_student.student_id
     *
     * @param studentId the value for t_task_student.student_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_student.student_num
     *
     * @return the value of t_task_student.student_num
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_student.student_num
     *
     * @param studentNum the value for t_task_student.student_num
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_student.student_name
     *
     * @return the value of t_task_student.student_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_student.student_name
     *
     * @param studentName the value for t_task_student.student_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_student.chanaged
     *
     * @return the value of t_task_student.chanaged
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getChanaged() {
        return chanaged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_student.chanaged
     *
     * @param chanaged the value for t_task_student.chanaged
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setChanaged(Integer chanaged) {
        this.chanaged = chanaged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_student.version
     *
     * @return the value of t_task_student.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_student.version
     *
     * @param version the value for t_task_student.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setVersion(Date version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_student.attaches
     *
     * @return the value of t_task_student.attaches
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getAttaches() {
        return attaches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_student.attaches
     *
     * @param attaches the value for t_task_student.attaches
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setAttaches(String attaches) {
        this.attaches = attaches == null ? null : attaches.trim();
    }
}