package com.xj.project.transform.model;

public class TaskConfig extends TaskConfigKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.mode_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer modeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.base_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long baseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.task_time_range
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String taskTimeRange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.tutor_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String tutorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.base_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String baseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.contact_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.contact_tel
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String contactTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.address
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.mode_id
     *
     * @return the value of t_task_config.mode_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getModeId() {
        return modeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.mode_id
     *
     * @param modeId the value for t_task_config.mode_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setModeId(Integer modeId) {
        this.modeId = modeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.base_id
     *
     * @return the value of t_task_config.base_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.base_id
     *
     * @param baseId the value for t_task_config.base_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setBaseId(Long baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.task_time_range
     *
     * @return the value of t_task_config.task_time_range
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getTaskTimeRange() {
        return taskTimeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.task_time_range
     *
     * @param taskTimeRange the value for t_task_config.task_time_range
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskTimeRange(String taskTimeRange) {
        this.taskTimeRange = taskTimeRange == null ? null : taskTimeRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.tutor_id
     *
     * @return the value of t_task_config.tutor_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getTutorId() {
        return tutorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.tutor_id
     *
     * @param tutorId the value for t_task_config.tutor_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTutorId(String tutorId) {
        this.tutorId = tutorId == null ? null : tutorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.base_name
     *
     * @return the value of t_task_config.base_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getBaseName() {
        return baseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.base_name
     *
     * @param baseName the value for t_task_config.base_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setBaseName(String baseName) {
        this.baseName = baseName == null ? null : baseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.contact_name
     *
     * @return the value of t_task_config.contact_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.contact_name
     *
     * @param contactName the value for t_task_config.contact_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.contact_tel
     *
     * @return the value of t_task_config.contact_tel
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getContactTel() {
        return contactTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.contact_tel
     *
     * @param contactTel the value for t_task_config.contact_tel
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setContactTel(String contactTel) {
        this.contactTel = contactTel == null ? null : contactTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.address
     *
     * @return the value of t_task_config.address
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.address
     *
     * @param address the value for t_task_config.address
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    @Override
    public String toString() {
        return "TaskConfig{" +
                ", taskId=" + getTaskId() +
                ", version=" + getVersion() +
                ", modeId=" + modeId +
                ", baseId=" + baseId +
                ", taskTimeRange='" + taskTimeRange + '\'' +
                ", tutorId='" + tutorId + '\'' +
                ", baseName='" + baseName + '\'' +
                ", contactName='" + contactName + '\'' +
                ", contactTel='" + contactTel + '\'' +
                ", address='" + address + '\'' +
                '}';
    }
}