package com.xj.project.transform.model;

import java.util.Date;

public class TaskConfigKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.task_id
     *
     * @return the value of t_task_config.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.task_id
     *
     * @param taskId the value for t_task_config.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config.version
     *
     * @return the value of t_task_config.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config.version
     *
     * @param version the value for t_task_config.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setVersion(Date version) {
        this.version = version;
    }
}