package com.xj.project.transform.model;

public class TaskConfigDetail extends TaskConfigDetailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_config_detail.config_detail
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String configDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_config_detail.config_detail
     *
     * @return the value of t_task_config_detail.config_detail
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getConfigDetail() {
        return configDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_config_detail.config_detail
     *
     * @param configDetail the value for t_task_config_detail.config_detail
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setConfigDetail(String configDetail) {
        this.configDetail = configDetail == null ? null : configDetail.trim();
    }
}