package com.xj.project.transform.model;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.title
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.description
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.arrange_type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer arrangeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.enroll_start_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date enrollStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.enroll_end_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date enrollEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.attaches
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String attaches;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.node_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.creator
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.create_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.type_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.task_start_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date taskStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.task_finish_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date taskFinishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task.notice_way
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String noticeWay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.id
     *
     * @return the value of t_task.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.id
     *
     * @param id the value for t_task.id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.school_id
     *
     * @return the value of t_task.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.school_id
     *
     * @param schoolId the value for t_task.school_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setSchoolId(Long schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.title
     *
     * @return the value of t_task.title
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.title
     *
     * @param title the value for t_task.title
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.description
     *
     * @return the value of t_task.description
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.description
     *
     * @param description the value for t_task.description
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.arrange_type
     *
     * @return the value of t_task.arrange_type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getArrangeType() {
        return arrangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.arrange_type
     *
     * @param arrangeType the value for t_task.arrange_type
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setArrangeType(Integer arrangeType) {
        this.arrangeType = arrangeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.enroll_start_time
     *
     * @return the value of t_task.enroll_start_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getEnrollStartTime() {
        return enrollStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.enroll_start_time
     *
     * @param enrollStartTime the value for t_task.enroll_start_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setEnrollStartTime(Date enrollStartTime) {
        this.enrollStartTime = enrollStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.enroll_end_time
     *
     * @return the value of t_task.enroll_end_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getEnrollEndTime() {
        return enrollEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.enroll_end_time
     *
     * @param enrollEndTime the value for t_task.enroll_end_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setEnrollEndTime(Date enrollEndTime) {
        this.enrollEndTime = enrollEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.attaches
     *
     * @return the value of t_task.attaches
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getAttaches() {
        return attaches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.attaches
     *
     * @param attaches the value for t_task.attaches
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setAttaches(String attaches) {
        this.attaches = attaches == null ? null : attaches.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.node_id
     *
     * @return the value of t_task.node_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.node_id
     *
     * @param nodeId the value for t_task.node_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.creator
     *
     * @return the value of t_task.creator
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.creator
     *
     * @param creator the value for t_task.creator
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.create_time
     *
     * @return the value of t_task.create_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.create_time
     *
     * @param createTime the value for t_task.create_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.status
     *
     * @return the value of t_task.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.status
     *
     * @param status the value for t_task.status
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.type_id
     *
     * @return the value of t_task.type_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.type_id
     *
     * @param typeId the value for t_task.type_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.task_start_time
     *
     * @return the value of t_task.task_start_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getTaskStartTime() {
        return taskStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.task_start_time
     *
     * @param taskStartTime the value for t_task.task_start_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskStartTime(Date taskStartTime) {
        this.taskStartTime = taskStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.task_finish_time
     *
     * @return the value of t_task.task_finish_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getTaskFinishTime() {
        return taskFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.task_finish_time
     *
     * @param taskFinishTime the value for t_task.task_finish_time
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskFinishTime(Date taskFinishTime) {
        this.taskFinishTime = taskFinishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task.notice_way
     *
     * @return the value of t_task.notice_way
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getNoticeWay() {
        return noticeWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task.notice_way
     *
     * @param noticeWay the value for t_task.notice_way
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setNoticeWay(String noticeWay) {
        this.noticeWay = noticeWay == null ? null : noticeWay.trim();
    }
}