package com.xj.project.transform.model;

import java.util.Date;

public class TaskGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_group.group_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_group.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_group.group_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_group.requirements
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String requirements;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_group.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private Date version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_task_group.attaches
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    private String attaches;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_group.group_id
     *
     * @return the value of t_task_group.group_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_group.group_id
     *
     * @param groupId the value for t_task_group.group_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_group.task_id
     *
     * @return the value of t_task_group.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_group.task_id
     *
     * @param taskId the value for t_task_group.task_id
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_group.group_name
     *
     * @return the value of t_task_group.group_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_group.group_name
     *
     * @param groupName the value for t_task_group.group_name
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_group.requirements
     *
     * @return the value of t_task_group.requirements
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getRequirements() {
        return requirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_group.requirements
     *
     * @param requirements the value for t_task_group.requirements
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setRequirements(String requirements) {
        this.requirements = requirements == null ? null : requirements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_group.version
     *
     * @return the value of t_task_group.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public Date getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_group.version
     *
     * @param version the value for t_task_group.version
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setVersion(Date version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_task_group.attaches
     *
     * @return the value of t_task_group.attaches
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public String getAttaches() {
        return attaches;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_task_group.attaches
     *
     * @param attaches the value for t_task_group.attaches
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    public void setAttaches(String attaches) {
        this.attaches = attaches == null ? null : attaches.trim();
    }
}