package com.xj.project.transform.dao;

import com.xj.project.transform.model.Journal;

public interface JournalDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_journal
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_journal
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insert(Journal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_journal
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insertSelective(Journal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_journal
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    Journal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_journal
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKeySelective(Journal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_journal
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKey(Journal record);
}