package com.xj.project.transform.dao;

import com.xj.project.transform.model.Node;

public interface NodeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insert(Node record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insertSelective(Node record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    Node selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKeySelective(Node record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_node
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKey(Node record);
}