package com.xj.project.transform.dao;

import com.xj.project.transform.model.Summary;
import com.xj.project.transform.model.SummaryWithBLOBs;

public interface SummaryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_summary
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_summary
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insert(SummaryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_summary
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insertSelective(SummaryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_summary
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    SummaryWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_summary
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKeySelective(SummaryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_summary
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SummaryWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_internship_summary
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKey(Summary record);
}