package com.xj.project.transform.dao;

import com.xj.project.transform.model.TaskGroup;

public interface TaskGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_group
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int deleteByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_group
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insert(TaskGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_group
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insertSelective(TaskGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_group
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    TaskGroup selectByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_group
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKeySelective(TaskGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_group
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKey(TaskGroup record);
}