package com.xj.project.transform.dao;

import com.xj.project.transform.model.TaskStudent;

public interface TaskStudentDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_student
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insert(TaskStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_student
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insertSelective(TaskStudent record);
}