package com.xj.project.transform.dao;

import com.xj.project.transform.model.TaskConfig;
import com.xj.project.transform.model.TaskConfigKey;
import com.xj.project.transform.utils.PageUtil;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

public interface TaskConfigDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int deleteByPrimaryKey(TaskConfigKey key);

    List<Map<String,Object>> findList(@Param("page")PageUtil page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insert(TaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insertSelective(TaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    List<TaskConfig> selectByPrimaryKey(TaskConfigKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKeySelective(TaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKey(TaskConfig record);
}