package com.xj.project.transform.dao;

import com.xj.project.transform.model.TaskConfigDetail;
import com.xj.project.transform.model.TaskConfigDetailKey;

public interface TaskConfigDetailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config_detail
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int deleteByPrimaryKey(TaskConfigDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config_detail
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insert(TaskConfigDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config_detail
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int insertSelective(TaskConfigDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config_detail
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    TaskConfigDetail selectByPrimaryKey(TaskConfigDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config_detail
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKeySelective(TaskConfigDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config_detail
     *
     * @mbg.generated Fri Mar 30 16:09:09 CST 2018
     */
    int updateByPrimaryKey(TaskConfigDetail record);
}